#!/usr/bin/env python3

from gi.repository import Gio
import json
import locale
import os
from pathlib import Path
import re
import subprocess
import sys

CONFIG_PATHS = {
	"relative": Path(__file__).parent.absolute() / "config",
	"global": Path("/usr/share/rofi-apps/config"),
	"user": Path.home() / ".config/rofi-apps/config"
}

ENTRIES_PATHS = [
	Path.home() / ".local/share/applications",
	Path("/usr/local/share/applications"),
	Path("/usr/share/applications")
]

CACHE_PATH = Path.home() / ".cache/rofi-apps"

def main():
	# Get rofi state
	ROFI_RETV = os.getenv("ROFI_RETV", 0)

	if ROFI_RETV == '1':
		entry = Entry(os.getenv("ROFI_INFO", ""))
		entry.launch()
		return
	else:
		showList()

def showList():
	"""Shows applications list"""

	# Read config
	if CONFIG_PATHS["user"].exists():
		config = Config(CONFIG_PATHS["user"])
	elif CONFIG_PATHS["global"].exists():
		config = Config(CONFIG_PATHS["global"])
	elif CONFIG_PATHS["relative"].exists():
		config = Config(CONFIG_PATHS["relative"])
	else:
		print(f"[!] Config not found.", file=sys.stderr)
		sys.exit(1)

	# Read from cache
	if isListCached(config):
		print(f"[?] Reading from cache", file=sys.stderr)
		with open(CACHE_PATH / "applist", "r") as cache:
			print(cache.read())
		return
	print(f"[?] Generating new list", file=sys.stderr)

	# Lists for storing entries
	entriesPinned = []
	entriesSorted = []

	entriesLength = 0

	for entriesPaths in ENTRIES_PATHS:
		for entryPath in entriesPaths.rglob("*.desktop"):
			entriesLength += 1

			# Skip directories
			if entryPath.is_dir():
				continue

			try:
				entry = Entry(str(entryPath))

				# Ignore hidden entries (NoDisplay=true)
				if entry.getNoDisplay():
					continue;

				# Ignore blacklisted entries
				if entry.isBlacklisted(config):
					continue

				# Ignore duplicated entries
				if entry.getFilename() in [e.getFilename() for e in entriesPinned + entriesSorted if e]:
					continue

				# Sort pinned entries
				entryIndex = entry.indexOfPinned(config)
				if entryIndex != -1:
					if len(entriesPinned) <= entryIndex:
						entriesPinned += [None] * (entryIndex - len(entriesPinned) + 1)
					entriesPinned[entryIndex] = entry
				else:
					entriesSorted.append(entry)

				# Edit entry following user defined rules
				entry.setCustoms(config)

			except TypeError as e:
				# Normally not a desktop entry, but print error anyway
				print(f"[@] TypeError while processing {entryPath}. Probably not a desktop entry.", file=sys.stderr)
				print(f"[@] {e}", file=sys.stderr)

	# Sort ordered list
	locale.setlocale(locale.LC_ALL, '')
	entriesSorted.sort(key=lambda entry: locale.strxfrm(entry.getName()))

	# Concatenate lists
	entries = entriesPinned + entriesSorted

	# Open cache file
	if not CACHE_PATH.exists():
		CACHE_PATH.mkdir(parents=True)

	with open(CACHE_PATH / "applist", "w") as cache:
		# Display final entries
		for entry in entries:
			if entry:
				entryString = f"{entry.getName()}\0icon\x1f{entry.getIcon()}\x1finfo\x1f{str(entry.getPath())}"
				print(entryString)
				cache.write(entryString + "\n")

	with open(CACHE_PATH / "cachedb", "w") as cache:
		# Update config mtime
		cache.write(f"{config.getPath().stat().st_mtime}\n")

		# Update desktop entries length
		cache.write(f"{entriesLength}\n")


def isListCached(config):
	"""
	Checks if applications list is cached and if it needs update

	Parameters:
		config - Config object

	Returns:
		result - True if list cache is up to date, False otherwise
	"""

	# No file - no cache
	if not (CACHE_PATH / "applist").exists():
		print(f"[?] No cache file", file=sys.stderr)
		return False

	with open(CACHE_PATH / "cachedb", "r") as cache:

		# Check if config changed
		configMtime = cache.readline()
		if config.getPath().stat().st_mtime != float(configMtime):
			print(f"[?] Config file changed", file=sys.stderr)
			return False

		# Check if desktop entries length changed
		entriesLength = int(cache.readline())
		for entriesPaths in ENTRIES_PATHS:
			entriesLength -= len([i for i in entriesPaths.rglob("*.desktop")])
		if entriesLength != 0:
			print(f"[?] Desktop entries length changed", file=sys.stderr)
			return False

	return True

class Config:
	"""
	Reads config file and does matching for custom entries

	Attributes:
		path - path to config file
		blacklist - list of blacklist rules
		pinned - list of pinned rules
		rename - list of custom name rules

	Methods:
		getPath() - Returns path to config
		getBlacklist() - Returns list of blacklisted entries rules
		getPinned() - Returns list of pinned entries rules
		getCustoms() - Returns list of custom entries rules and values
	"""

	def __init__(self, path):
		"""
		Open config file and extract blacklist and pinned rules

		Parameters:
			path - path to config file
		"""

		with open(path, "r") as f:
			configJson = f.read()
			configJson = re.sub("//.*?$", "", configJson, flags=re.M)
			config = json.loads(configJson)
			self.path = path
			self.blacklist = config["blacklist"]
			self.pinned = config["pinned"]
			self.customs = config["customs"]

	def getPath(self):
		"""Returns path to config"""
		return self.path

	def getBlacklist(self):
		"""Returns list of blacklisted entries rules"""
		return self.blacklist

	def getPinned(self):
		"""Returns list of pinned entries rules"""
		return self.pinned

	def getCustoms(self):
		"""Returns list of custom entries rules and values"""
		return self.customs

class Entry():
	"""
	Wrapper class for Gio.DesktopAppInfo object. Includes additional
	methods for filtering entries.

	Attributes:
		entry - Gio.DesktopAppInfo object containing actual entry data
		customName - custom name for entry set by user

	Methods:
		isBlacklisted(config) - Check if desktop entry is blacklisted
		isPinned(config) - Check if desktop entry is pinned
		matchRule(rule) - Check if rule matches the desktop entry
		setCustoms() - Set custom properties for the desktop entry
		launch() - Starts entry's application
		getNoDisplay() - Returns NoDisplay value
		getName() - Returns Name or Custom name (if set)
		getCommandLine() - Returns Exec value
		getPath() - Returns path to desktop entry file
		getFilename() - Returns name of desktop entry file
		getIcon() - Returns string representation of entry's icon
		getEntryId() - Returns absolute desktop entry id
	"""

	def __init__(self, path):
		"""
		Open desktop entry file and read its properties to Gio.DesktopAppInfo object

		Parameters:
			path - path to desktop entry file
		"""

		self.entry = Gio.DesktopAppInfo.new_from_filename(path)
		self.customName = None

	def isBlacklisted(self, config):
		"""
		Check if desktop entry is blacklisted

		Parameters:
			config - Config object containing blacklist

		Returns:
		result - true if entry is blacklisted, false otherwise
		"""

		# Check every rule until one matches
		for rule in config.getBlacklist():
			if self.matchRule(rule):
				return True
		return False

	def indexOfPinned(self, config):
		"""
		Gets index of pinned entry

		Parameters:
			config - Config object containing list of pinned entries rules

		Returns:
		i - index of rule if entry is pinned, otherwise -1
		"""

		# Check every rule until one matches
		i = 0
		for rule in config.getPinned():
			if self.matchRule(rule):
				return i
			i += 1
		return -1;

	def setCustoms(self, config):
		"""
		Set custom properties for the desktop entry

		Parameters:
			config - Config object containing list of custom rules
		"""

		for rule in config.getCustoms():
			if self.matchRule(rule):
				if "newName" in rule:
					self.customName = rule["newName"]
				break

	def launch(self):
		"""Starts entry's application"""
		print(f"[?] Launching {self.getName()} ({self.entry.get_name()})", file=sys.stderr)
		print(f"[?] Desktop entry id: {self.getEntryId()}", file=sys.stderr)
		print(f"[?] Desktop entry path: {str(self.getPath())}", file=sys.stderr)
		subprocess.Popen(['gtk-launch', self.getEntryId()], close_fds=True, start_new_session=True, stdout=subprocess.DEVNULL)

	def matchRule(self, rule):
		"""
		Check if rule matches the desktop entry

		Parameters:
			rule - the rule for checking the entry

		Returns:
		result - true if rule matches the entry, false otherwise
		"""

		if not len(rule):
			return False

		match = True
		if "name" in rule:
			match &= True if re.search(rule["name"], self.getName()) else False
		if "exec" in rule:
			match &= True if re.search(rule["exec"], self.getCommandLine()) else False
		return match

	def getNoDisplay(self):
		"""Returns NoDisplay value"""
		return self.entry.get_nodisplay()

	def getName(self):
		"""Returns Name or Custom name (if set)"""
		if self.customName:
			return self.customName
		else:
			return self.entry.get_name()

	def getCommandLine(self):
		"""Returns Exec value"""
		return self.entry.get_commandline()

	def getFilename(self):
		"""Returns name of desktop entry file"""
		return self.getPath().name

	def getPath(self):
		"""Returns path to desktop entry file"""
		return Path(self.entry.get_filename())

	def getIcon(self):
		"""Returns string representation of entry's icon"""
		try:
			icon = self.entry.get_icon()
			if not icon:
				return None
			if isinstance(icon, Gio.FileIcon):
				return icon.get_file().get_path()
			if isinstance(icon, Gio.ThemedIcon):
				return icon.get_names()[0]

		except AttributeError as e:
			print(f"[!] AttributeError while reading icon file of {self.getFilename()}.", file=sys.stderr)
			print(f"[!] {e}.", file=sys.stderr)
			return None

	def getEntryId(self):
		"""Returns absolute desktop entry id"""
		path = self.getPath()
		for entriesPaths in ENTRIES_PATHS:
			if not path.is_relative_to(entriesPaths):
				continue
			relativePath = path.relative_to(entriesPaths)
			return str(relativePath.parent / relativePath.stem).replace("/", "-")
		return str(path.stem).replace("/", "-")


if __name__ == "__main__":
	main()